### ISSUE TITLE
Remove hard-coded path

### ISSUE THREAD

**Issue by emlys** [natcap/schistosomiasis#13]
A path is hard-coded to a location which doesn't exist on other computers:
https://github.com/natcap/schistosomiasis/blob/c50e42ea6e36af6b4967dcfa4a0dcb39d8466820/src/natcap/invest/schistosomiasis.py#L946-L948

**Comment by dcdenu4** [comment]
Thanks! I've already refactored this and will push up a fix shortly.

**Comment by dcdenu4** [comment]
Fixed. Color profiles are now stored in as constants and saved to disk during the model run.
